#!/usr/bin/env zsh

profile=$(find ~/.config/qutebrowser -mindepth 1 -maxdepth 1 '!' -name base -type d -printf '%P\n' | tpeco --fullscreen)

if [[ -n $profile ]]; then
    if [[ $profile = "dev" ]]; then
        qutebrowser --basedir ~/.config/qutebrowser/dev --enable-webengine-inspector $@ &
    elif [[ -d ~/.config/qutebrowser/$profile ]]; then
        qutebrowser --basedir ~/.config/qutebrowser/$profile $@ &
    else
        echo "Profile $profile does not exist, please create it"
    fi
else
    echo "Empty selection, cancelling"
fi
