#!/bin/bash

file=/data/Pictures/Screenshots/$(date +%y-%m-%d_%H-%M-%S).png
: ${site:=puu.sh}
regex="^(https?|ftp)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]$"

if [[ "$1" == "desktop" ]]; then
	maim $file
elif [[ "$1" == "current" ]]; then
	maim -i $(xdotool getactivewindow) $file
else
	maim -s $file
fi

if [ -f $file ]; then
	url=$($site $file)

	filename=$(basename $file)

	if [[ "$url" =~ $regex ]]; then
		echo -n $url | xclip -selection clipboard
		notify-send -i $file $filename "Uploaded successfully"
	else
		notify-send -i $file $filename "Failed to upload"
	fi
fi
