#!/bin/zsh

if [[ $1 = 8 ]]; then
    btns=( Super_L )
elif [[ $1 = 9 ]]; then
    # functionality of Hyper_L
    btns=( Alt_L )
else
    echo "Not implemented for this button"
    exit 1
fi

cmd="xinput --query-state 'Kingsis Peripherals ZOWIE Gaming mouse' | grep '\[$1\]' | cut -c 12-"
state=$(eval $cmd)

while [[ $state = "down" ]]; do
  echo $state $btns
  state=$(eval $cmd)
  sleep 0.01
done

echo $state $btns

for btn in $btns; do
    xte 'keyup '$btn''
    echo keyup $btn
done
